/**
 * Manually curated brommer (moped) toertochten that are NOT covered by the
 * brommerritten.nl feed (scrapeTribe, see VENUES in scrape.mjs): multi-day tours,
 * beurzen, and everything in België (oldtimerweb.be's "bromfietsen" filter was
 * checked and does not reliably include these specific club rides — see
 * docs/CONTENT.md). Add new entries with an id, title, ISO start/end (with
 * timezone offset), location, country, url and tags, after verifying date/url
 * via web search. Past events are filtered out automatically by the scraper.
 */
export const MANUAL_BROMMER = [
  // Nederland (not on brommerritten.nl: multi-day tours & a beurs, not "ritten")
  {
    id: 'motovelo-rosmalen-2026',
    title: 'MotoVelo',
    start: '2026-01-10T10:00:00+01:00',
    end: '2026-01-11T17:00:00+01:00',
    location: 'Autotron, Graafsebaan 133, Rosmalen',
    country: 'Nederland',
    description: 'Beurs met klassieke motoren, bromfietsen en fietsen, 100+ stands.',
    url: 'https://www.autotron.nl/evenement/motovelo-2026/',
    tags: ['Beurs'],
  },
  {
    id: 'rust-n-dust-brommerweekend-2026',
    title: "Rust 'N Dust Brommerweekend",
    start: '2026-05-15T15:00:00+02:00',
    end: '2026-05-18T12:00:00+02:00',
    location: 'Lhee/Dwingeloo (Drenthe)',
    country: 'Nederland',
    description: 'Camping-weekend met kampvuur, dagelijks ontbijt, BBQ op zaterdagavond, feestje en campingkroeg.',
    url: 'https://rustndustrally.nl/edities/brommerweekend/brommerweekend-2026/',
    tags: ['Camping', 'Weekend'],
  },
  {
    id: 'rust-n-dust-brommereditie-2026',
    title: "Rust 'N Dust Brommereditie",
    start: '2026-08-03T09:00:00+02:00',
    end: '2026-08-07T17:00:00+02:00',
    location: 'Duitsland, Luxemburg & Frankrijk (5-daagse tour)',
    description: '5-daagse brommertocht door Duitsland, Luxemburg en Frankrijk, elke dag een andere camping, terug naar start/finish.',
    url: 'https://rustndustrally.nl/edities/brommer/brommereditie-2026/',
    tags: ['Meerdaagse tour'],
  },
  {
    id: 'rhc-stramproy-2026',
    title: 'RHC Toertocht & Hulpmotoren Treffen',
    start: '2026-09-12T09:00:00+02:00',
    end: '2026-09-13T17:00:00+02:00',
    location: 'Stramproy (Limburg)',
    country: 'Nederland',
    description: 'Weekend voor rijwielen met hulpmotor en bromfietsen tot bouwjaar 1959. Zaterdag alleen authentieke hulpmotorfietsen, zondag toertocht (deels over Belgisch grondgebied). Gezamenlijk ontbijt en BBQ voor overnachters.',
    url: 'https://www.brommer.nl/evenementen/rhc-hulpmotoren-treffen-stramproy/',
    tags: ['Toertocht', 'Hulpmotor'],
  },

  // België (geen betrouwbare automatische bron gevonden, zie docs/CONTENT.md)
  {
    id: 'aardbeirit-melsele-2026',
    title: '18de Aardbeirit',
    start: '2026-05-16T13:00:00+02:00',
    end: '2026-05-16T18:00:00+02:00',
    location: 'Kerkplein, Melsele (Oost-Vlaanderen)',
    country: 'België',
    description: 'Rit tijdens de Aardbeifeesten. Bromfietsroute 50 km incl. rallyplaat, roadboek, drankbon en aardbeien (€15).',
    url: 'https://www.oldtimerweb.be/oldtimer-evenementen/20091-18de-aardbeirit-voor-oldtimer-bromfietsen-en-autos',
    tags: ['Toertocht'],
  },
  {
    id: 'boms-veteranentour-2026',
    title: "BOM's Veteranentour",
    start: '2026-06-27T08:00:00+02:00',
    end: '2026-06-28T18:00:00+02:00',
    location: 'Berlare → Houffalize → Berlare',
    country: 'België',
    description: 'Tweedaagse rit van 600+ km door Vlaanderen en Wallonië, vooral voor motoren van vóór 1960, bromfietsen welkom. Georganiseerd door de Berlaarse Oldtimer Motorvrienden.',
    url: 'https://www.bomberlare.be/',
    tags: ['Meerdaagse tour'],
  },
  {
    id: 'ardennenrit-sint-truiden-2026',
    title: 'Ardennenrit',
    start: '2026-08-02T09:00:00+02:00',
    end: '2026-08-02T18:00:00+02:00',
    location: 'The Roadhouse, Melveren (Sint-Truiden)',
    country: 'België',
    description: '30ste Ardennenrit van VVK Beringen, ca. 180 km richting de Ardennen.',
    url: 'https://www.oldtimerweb.be/oldtimer-rondritten',
    tags: ['Toertocht'],
  },
  {
    id: 'aa-beeckrit-bree-2026',
    title: 'Aa-Beeckrit',
    start: '2026-08-09T09:00:00+02:00',
    end: '2026-08-09T17:00:00+02:00',
    location: 'Neerstraat 9, Bree (Limburg)',
    country: 'België',
    description: '28ste internationale bijeenkomst voor motoren en bromfietsen van vóór 1975. Route van 110 km (motoren) of 70 km (bromfietsen) door de Abeek-streek.',
    url: 'https://www.oldtimerweb.be/oldtimer-evenementen/20994-aa-beeckrit',
    tags: ['Toertocht'],
  },
  {
    id: 'torhoutse-kastelentocht-2026',
    title: 'Torhoutse Oldtimer Kastelentocht',
    start: '2026-08-15T08:00:00+02:00',
    end: '2026-08-15T17:00:00+02:00',
    location: 'Zaal De Mast, Industrielaan 3, Torhout (West-Vlaanderen)',
    country: 'België',
    description: "44e editie, kastelenroute door het Brugse Ommeland en het Houtland voor voertuigen van vóór 1940. Rond 16:00 stop op de Torhoutse markt.",
    url: 'https://www.uitinvlaanderen.be/agenda/e/oldtimer-kastelentocht/9399ad28-45e2-427b-8c73-2c1d418f69ff',
    tags: ['Toertocht', 'Kastelenroute'],
  },
  {
    id: 'avondrit-maaseiker-2026',
    title: 'Avondrit Maaseiker Oldtimer Club',
    start: '2026-08-15T17:00:00+02:00',
    end: '2026-08-15T22:00:00+02:00',
    location: 'Emiel Van Dorenlaan 144, Genk (Limburg)',
    country: 'België',
    description: 'Avondrit van ca. 70 km, aankomst bij Katapultclub Rosse Lei in Bree. Optioneel BBQ na afloop.',
    url: 'https://www.oldtimerweb.be/oldtimer-evenementen/21077-avondrit-maaseiker-oldtimer-club',
    tags: ['Avondrit'],
  },
  {
    id: 'serskampse-oldtimer-tour-2026',
    title: 'Serskampse Oldtimer Tour',
    start: '2026-08-23T09:00:00+02:00',
    end: '2026-08-23T17:00:00+02:00',
    location: 'Terreinen Esveeka, Nieuwstraat 48D, Serskamp',
    country: 'België',
    description: "11de editie ('Dress 'n Ride'), open voor alle oldtimers incl. bromfietsen en scooters. Live muziek, kinderanimatie en marktkramen.",
    url: 'http://serskampseoldtimertour.be/',
    tags: ['Toertocht', 'Beurs'],
  },
  {
    id: 'bromfietstreffen-wellen-2026',
    title: 'Bromfietstreffen Wellen',
    start: '2026-09-06T08:00:00+02:00',
    end: '2026-09-06T17:00:00+02:00',
    location: 'Wellen (Limburg)',
    country: 'België',
    description: 'Bromfietstreffen voor brommers van vóór 1995, met 2 georganiseerde ritten en een doorlopende onderdelenbeurs.',
    url: 'https://www.brommer.nl/evenementen/int-bromfietstreffen-wellen/',
    tags: ['Treffen', 'Onderdelenbeurs'],
  },
]
